spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.216:3306/yb_datacenter?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: yibai123456
  thymeleaf:
    cache: false
    mode: HTML5
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait:
    password: ''
  mongo:
    connectionsPerHost: 5000
    dbname: admin
    mongoDatabaseAddress: dp.yibai-it.com:10035
    password: root
    username: yibai123456
logging:
  level:
    com:
      example:
        demo:
          mapper: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8008

file:
  upload-dir: ./src/main/resources/static/image



