spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: yibai123456
    url: jdbc:mysql://192.168.71.216:3306/yb_datacenter?useUnicode=true&characterEncoding=UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8888
