spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 
    url: jdbc:
  thymeleaf:
    cache: false
    mode: HTML5
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait:
    password: ''
  mongo:
    connectionsPerHost: 50
    dbname: 
    mongoDatabaseAddress: 
    password: 
    username: 

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8008
winit:
 account:

 list:
   - default
   - api
   - kevin


