spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_class_style?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: HTML5
logging:
  level:
    com:
      example:
        demo:
          mapper: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8090

file:
  upload-dir: ./src/main/resources/static/image



